from .cart import (
    cart_add,
    cart_detail,
    cart_remove,
    cart_update,
)
from .clients import (
    ClientCreateView,
    ClientDeleteView,
    ClientDetailView,
    ClientListView,
    ClientUpdateView,
)
from .company import (
    CompanySettingsView,
)
from .dashboard import (
    DashboardView,
)
from .expenses import (
    ExpenseCreateView,
    ExpenseDeleteView,
    ExpenseDetailView,
    ExpenseInstallmentCreateView,
    ExpenseInstallmentDeleteView,
    ExpenseInstallmentUpdateView,
    ExpenseListView,
    ExpenseUpdateView,
    installment_cancel_payment,
    installment_pay,
)
from .imports import (
    product_import_mapping,
    product_import_upload,
)
from .invoices import (
    InboundInvoiceCreateView,
    InboundInvoiceDeleteView,
    InboundInvoiceDetailView,
    InboundInvoiceListView,
    InboundInvoiceUpdateView,
    InvoiceDuplicateCreateView,
    InvoiceDuplicateDeleteView,
    InvoiceDuplicateUpdateView,
    InvoiceItemCreateView,
    InvoiceItemDeleteView,
    InvoiceItemUpdateView,
    invoice_process,
)
from .manufacturers import (
    ManufacturerCreateView,
    ManufacturerDeleteView,
    ManufacturerListView,
    ManufacturerUpdateView,
)
from .products import (
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductToggleActiveView,
    ProductUpdateView,
)
from .reports import (
    report_index,
    report_render,
)
from .sales import (
    SaleDetailView,
    SaleListView,
    checkout,
    sale_quote,
    sale_receipt,
)
from .suppliers import (
    RepresentativeCreateView,
    RepresentativeDeleteView,
    RepresentativeUpdateView,
    SupplierCreateView,
    SupplierDeleteView,
    SupplierDetailView,
    SupplierListView,
    SupplierUpdateView,
)

__all__ = [
    "cart_add",
    "cart_detail",
    "cart_remove",
    "cart_update",
    "ClientCreateView",
    "ClientDeleteView",
    "ClientDetailView",
    "ClientListView",
    "ClientUpdateView",
    "CompanySettingsView",
    "DashboardView",
    "ExpenseCreateView",
    "ExpenseDeleteView",
    "ExpenseDetailView",
    "ExpenseInstallmentCreateView",
    "ExpenseInstallmentDeleteView",
    "ExpenseInstallmentUpdateView",
    "ExpenseListView",
    "ExpenseUpdateView",
    "installment_pay",
    "installment_cancel_payment",
    "InboundInvoiceCreateView",
    "InboundInvoiceDeleteView",
    "InboundInvoiceDetailView",
    "InboundInvoiceListView",
    "InboundInvoiceUpdateView",
    "InvoiceDuplicateCreateView",
    "InvoiceDuplicateDeleteView",
    "InvoiceDuplicateUpdateView",
    "InvoiceItemCreateView",
    "InvoiceItemDeleteView",
    "InvoiceItemUpdateView",
    "ManufacturerCreateView",
    "ManufacturerDeleteView",
    "ManufacturerListView",
    "ManufacturerUpdateView",
    "ProductCreateView",
    "ProductDeleteView",
    "ProductDetailView",
    "ProductListView",
    "ProductToggleActiveView",
    "ProductUpdateView",
    "product_import_upload",
    "product_import_mapping",
    "report_index",
    "report_render",
    "checkout",
    "sale_quote",
    "sale_receipt",
    "SaleDetailView",
    "SaleListView",
    "RepresentativeCreateView",
    "RepresentativeDeleteView",
    "RepresentativeUpdateView",
    "SupplierCreateView",
    "SupplierDeleteView",
    "SupplierDetailView",
    "SupplierListView",
    "SupplierUpdateView",
]
