# Generated by Django 5.2 on 2026-06-12 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Código de barras')),
                ('manufacturer_code', models.CharField(blank=True, max_length=64, verbose_name='Código do fabricante')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade')),
                ('unit_type', models.CharField(choices=[('unid', 'Unidade'), ('pct', 'Pacote'), ('kg', 'Quilograma'), ('g', 'Grama'), ('mg', 'Miligrama'), ('km', 'Quilômetro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('l', 'Litro'), ('ml', 'Mililitro')], default='unid', max_length=4, verbose_name='Tipo de unidade')),
                ('unit_price_cents', models.PositiveIntegerField(default=0, verbose_name='Preço unitário (centavos)')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sign.manufacturer', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
