# Generated by Django 5.2 on 2026-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('person_type', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo de pessoa')),
                ('service_provider', models.BooleanField(default=False, verbose_name='Prestador de serviço')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone_primary', models.CharField(blank=True, max_length=20, verbose_name='Telefone principal')),
                ('phone_primary_is_whatsapp', models.BooleanField(default=False, verbose_name='Telefone principal é WhatsApp')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Telefone alternativo')),
                ('phone_secondary_is_whatsapp', models.BooleanField(default=False, verbose_name='Telefone alternativo é WhatsApp')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='Complemento')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='Código postal')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
