# Generated by Django 5.2 on 2026-06-20 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Código de barras')),
                ('manufacturer_name', models.CharField(max_length=120, verbose_name='Fabricante')),
                ('manufacturer_code', models.CharField(blank=True, max_length=64, verbose_name='Código do fabricante')),
                ('unit_type', models.CharField(choices=[('unid', 'Unidade'), ('pct', 'Pacote'), ('kg', 'Quilograma'), ('g', 'Grama'), ('mg', 'Miligrama'), ('km', 'Quilômetro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('l', 'Litro'), ('ml', 'Mililitro')], max_length=4, verbose_name='Tipo de unidade')),
                ('content_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash do conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='sign.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Snapshot de produto',
                'verbose_name_plural': 'Snapshots de produto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_cents', models.PositiveIntegerField(default=0, verbose_name='Subtotal (centavos)')),
                ('has_perc_discount', models.BooleanField(default=False, verbose_name='Desconto percentual')),
                ('perc_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de desconto')),
                ('discount_cents', models.PositiveIntegerField(default=0, verbose_name='Desconto (centavos)')),
                ('change_cents', models.PositiveIntegerField(default=0, verbose_name='Troco (centavos)')),
                ('total_cents', models.PositiveIntegerField(default=0, verbose_name='Total (centavos)')),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sign.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('unit_price_cents', models.PositiveIntegerField(default=0, verbose_name='Preço unitário (centavos)')),
                ('subtotal_cents', models.PositiveIntegerField(default=0, verbose_name='Subtotal (centavos)')),
                ('has_perc_discount', models.BooleanField(default=False, verbose_name='Desconto percentual')),
                ('perc_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de desconto')),
                ('discount_cents', models.PositiveIntegerField(default=0, verbose_name='Desconto (centavos)')),
                ('total_cents', models.PositiveIntegerField(default=0, verbose_name='Total (centavos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='sign.productsnapshot', verbose_name='Snapshot do produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sign.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da venda',
                'verbose_name_plural': 'Itens da venda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('pix', 'Pix'), ('other', 'Outros')], max_length=8, verbose_name='Forma de pagamento')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
                ('value_cents', models.PositiveIntegerField(default=0, verbose_name='Valor (centavos)')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sign.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('sale', 'payment_type'), name='uniq_sale_payment_type')],
            },
        ),
    ]
