# Generated by Django 5.2 on 2026-06-27 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_productsnapshot_sale_saleitem_salepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('recurrent', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('scheduled_for', models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês (1–31) usado quando a despesa é recorrente.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia previsto de vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_current', models.PositiveIntegerField(default=1, verbose_name='Parcela')),
                ('installment_total', models.PositiveIntegerField(default=1, verbose_name='Total de parcelas')),
                ('value_cents', models.PositiveIntegerField(default=0, verbose_name='Valor (centavos)')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('paid_value_cents', models.PositiveIntegerField(default=0, verbose_name='Valor pago (centavos)')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sign.expense', verbose_name='Despesa')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['due_date', 'installment_current'],
            },
        ),
    ]
