# Generated by Django 5.2 on 2026-07-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_client_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Razão social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone_primary', models.CharField(blank=True, max_length=20, verbose_name='Telefone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Telefone alternativo')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='Complemento')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='Código postal')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
    ]
