# Generated by Django 5.2 on 2026-07-06 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0008_seed_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('state_registration', models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual')),
                ('multiple_brands', models.BooleanField(default=True, verbose_name='Trabalha com múltiplas marcas')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone_primary', models.CharField(blank=True, max_length=20, verbose_name='Telefone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Telefone alternativo')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Usado quando o fornecedor não trabalha com múltiplas marcas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='sign.manufacturer', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone_primary', models.CharField(blank=True, max_length=20, verbose_name='Telefone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Telefone alternativo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='sign.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['name'],
            },
        ),
    ]
