# Generated by Django 5.2 on 2026-07-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0009_supplier_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_obs',
            field=models.TextField(blank=True, verbose_name='Observações do desconto'),
        ),
    ]
