# Generated by Django 5.2 on 2026-07-06 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0010_sale_discount_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Número da nota')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Data de entrega')),
                ('products_total_cents', models.PositiveIntegerField(default=0, verbose_name='Valor total dos produtos (centavos)')),
                ('total_cents', models.PositiveIntegerField(default=0, verbose_name='Valor total (centavos)')),
                ('icms_base_cents', models.PositiveIntegerField(default=0, verbose_name='Base de cálculo do ICMS (centavos)')),
                ('icms_cents', models.PositiveIntegerField(default=0, verbose_name='Valor do ICMS (centavos)')),
                ('ipi_cents', models.PositiveIntegerField(default=0, verbose_name='Valor do IPI (centavos)')),
                ('taxes_total_cents', models.PositiveIntegerField(default=0, verbose_name='Valor total dos tributos (centavos)')),
                ('freight_cents', models.PositiveIntegerField(default=0, verbose_name='Valor do frete (centavos)')),
                ('insurance_cents', models.PositiveIntegerField(default=0, verbose_name='Valor do seguro (centavos)')),
                ('discount_cents', models.PositiveIntegerField(default=0, verbose_name='Valor do desconto (centavos)')),
                ('other_costs_cents', models.PositiveIntegerField(default=0, verbose_name='Outras despesas acessórias (centavos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sign.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota fiscal de entrada',
                'verbose_name_plural': 'Notas fiscais de entrada',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('value_cents', models.PositiveIntegerField(default=0, verbose_name='Valor (centavos)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='sign.inboundinvoice', verbose_name='Nota fiscal')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Código do produto')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição do produto')),
                ('unit_type', models.CharField(choices=[('unid', 'Unidade'), ('pct', 'Pacote'), ('kg', 'Quilograma'), ('g', 'Grama'), ('mg', 'Miligrama'), ('km', 'Quilômetro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('l', 'Litro'), ('ml', 'Mililitro')], default='unid', max_length=4, verbose_name='Tipo de unidade')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantidade')),
                ('unit_price_cents', models.PositiveIntegerField(default=0, verbose_name='Valor unitário (centavos)')),
                ('total_cents', models.PositiveIntegerField(default=0, verbose_name='Valor total (centavos)')),
                ('icms_base_cents', models.PositiveIntegerField(default=0, verbose_name='Base de cálculo do ICMS (centavos)')),
                ('icms_cents', models.PositiveIntegerField(default=0, verbose_name='Valor ICMS (centavos)')),
                ('ipi_cents', models.PositiveIntegerField(default=0, verbose_name='Valor IPI (centavos)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sign.inboundinvoice', verbose_name='Nota fiscal')),
            ],
            options={
                'verbose_name': 'Produto da nota',
                'verbose_name_plural': 'Produtos da nota',
                'ordering': ['id'],
            },
        ),
    ]
