# Generated by Django 5.2 on 2026-07-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0011_inboundinvoice_invoiceduplicate_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='daily_sales_goal_cents',
            field=models.PositiveIntegerField(default=0, verbose_name='Meta de venda diária (centavos)'),
        ),
        migrations.AddField(
            model_name='company',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='Estoque baixo'),
        ),
        migrations.AddField(
            model_name='company',
            name='operating_days_per_week',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=6, verbose_name='Dias de operação na semana'),
        ),
        migrations.AddField(
            model_name='company',
            name='price_multiplier',
            field=models.FloatField(default=1.0, verbose_name='Fator multiplicativo de preço'),
        ),
        migrations.AddField(
            model_name='company',
            name='rounding_type',
            field=models.CharField(choices=[('cent', 'Centavo'), ('cent_10', 'Centavo (Múltiplo de 10)'), ('real', 'Real'), ('real_2', 'Real (Múltiplo de 2)'), ('real_5', 'Real (Múltiplo de 5)'), ('real_10', 'Real (Múltiplo de 10)')], default='cent', max_length=8, verbose_name='Tipo de arredondamento'),
        ),
    ]
