# Generated by Django 5.2 on 2026-07-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0012_company_daily_sales_goal_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque mínimo'),
        ),
        migrations.AddField(
            model_name='product',
            name='nf_search_id',
            field=models.TextField(blank=True, help_text="IDs de referência usados por fornecedores, separados por ';'.", verbose_name='IDs de busca para NF'),
        ),
    ]
