# Generated by Django 5.2 on 2026-07-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0013_product_is_active_product_min_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundinvoice',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Processada'),
        ),
        migrations.AddField(
            model_name='inboundinvoice',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processada em'),
        ),
    ]
