# Generated by Django 5.2 on 2026-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0014_inboundinvoice_processed_inboundinvoice_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinstallment',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Código de barras'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'quantity'], name='sign_produc_is_acti_b1e7b9_idx'),
        ),
    ]
