# Generated by Django 5.2 on 2026-07-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0015_alter_expenseinstallment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rounding_type',
            field=models.CharField(choices=[('cent', 'Centavo'), ('cent_10', 'Centavo (Múltiplo de 10)'), ('cent_50', 'Centavo (Múltiplo de 50)'), ('real', 'Real'), ('real_2', 'Real (Múltiplo de 2)'), ('real_5', 'Real (Múltiplo de 5)'), ('real_10', 'Real (Múltiplo de 10)')], default='cent', max_length=8, verbose_name='Tipo de arredondamento'),
        ),
    ]
