# Generated by Django 5.2 on 2026-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0016_alter_company_rounding_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='receipt_product_code',
            field=models.CharField(choices=[('barcode', 'Código de barras'), ('manufacturer', 'Código do fabricante'), ('none', 'Nenhum')], default='barcode', max_length=12, verbose_name='Código de produto em comprovantes/orçamentos'),
        ),
        migrations.AddField(
            model_name='company',
            name='receipt_store_name',
            field=models.CharField(choices=[('name', 'Nome'), ('legal_name', 'Razão social'), ('blank', 'Em branco (manter espaço)')], default='name', max_length=10, verbose_name='Nome exibido em comprovantes/orçamentos'),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_show_barcode',
            field=models.BooleanField(default=True, verbose_name='Mostrar código de barras nas telas de venda'),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_show_manufacturer_code',
            field=models.BooleanField(default=True, verbose_name='Mostrar código do fabricante nas telas de venda'),
        ),
    ]
