# Generated by Django 5.2 on 2026-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0017_company_receipt_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='receipt_store_name',
            field=models.CharField(choices=[('name', 'Nome'), ('legal_name', 'Razão social'), ('blank', 'Em branco (manter espaço)')], default='name', max_length=10, verbose_name='Nome exibido em comprovantes, orçamentos e relatórios'),
        ),
    ]
