# Generated by Django 5.2 on 2026-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0018_alter_company_receipt_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(choices=[('-12:00', 'UTC-12:00'), ('-11:00', 'UTC-11:00'), ('-10:00', 'UTC-10:00'), ('-09:00', 'UTC-09:00'), ('-08:00', 'UTC-08:00'), ('-07:00', 'UTC-07:00'), ('-06:00', 'UTC-06:00'), ('-05:00', 'UTC-05:00 (Rio Branco)'), ('-04:00', 'UTC-04:00 (Manaus)'), ('-03:00', 'UTC-03:00 (Brasília)'), ('-02:00', 'UTC-02:00 (Fernando de Noronha)'), ('-01:00', 'UTC-01:00'), ('+00:00', 'UTC±00:00'), ('+01:00', 'UTC+01:00'), ('+02:00', 'UTC+02:00'), ('+03:00', 'UTC+03:00'), ('+04:00', 'UTC+04:00'), ('+05:00', 'UTC+05:00'), ('+06:00', 'UTC+06:00'), ('+07:00', 'UTC+07:00'), ('+08:00', 'UTC+08:00'), ('+09:00', 'UTC+09:00'), ('+10:00', 'UTC+10:00'), ('+11:00', 'UTC+11:00'), ('+12:00', 'UTC+12:00'), ('+13:00', 'UTC+13:00'), ('+14:00', 'UTC+14:00')], default='+00:00', max_length=6, verbose_name='Fuso horário'),
        ),
    ]
