# Generated by Django 5.2 on 2026-10-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0019_company_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='declared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Declarada em'),
        ),
    ]
